baseurl = "https://example.com/"
publishDir = "docs"
languageCode = "en-US"
title = "Rising Voices Youth Choir"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "rvyc.png"
  author = "Rising Voices Youth Choir"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "academyformusic@gmail.com"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "events"
  identifier = "events"
  weight = 200
  url = "/events/"
[[menu.main]]
  name = "videos"
  identifier = "videos"
  weight = 300
  url = "/videos/"
